In [5]:
import gensim.downloader as api
model = api.load("glove-wiki-gigaword-100")


[==================================================] 100.0% 128.1/128.1MB downloaded


In [7]:
word_vectors = model

print(word_vectors['computer'])

[-1.6298e-01  3.0141e-01  5.7978e-01  6.6548e-02  4.5835e-01 -1.5329e-01
  4.3258e-01 -8.9215e-01  5.7747e-01  3.6375e-01  5.6524e-01 -5.6281e-01
  3.5659e-01 -3.6096e-01 -9.9662e-02  5.2753e-01  3.8839e-01  9.6185e-01
  1.8841e-01  3.0741e-01 -8.7842e-01 -3.2442e-01  1.1202e+00  7.5126e-02
  4.2661e-01 -6.0651e-01 -1.3893e-01  4.7862e-02 -4.5158e-01  9.3723e-02
  1.7463e-01  1.0962e+00 -1.0044e+00  6.3889e-02  3.8002e-01  2.1109e-01
 -6.6247e-01 -4.0736e-01  8.9442e-01 -6.0974e-01 -1.8577e-01 -1.9913e-01
 -6.9226e-01 -3.1806e-01 -7.8565e-01  2.3831e-01  1.2992e-01  8.7721e-02
  4.3205e-01 -2.2662e-01  3.1549e-01 -3.1748e-01 -2.4632e-03  1.6615e-01
  4.2358e-01 -1.8087e+00 -3.6699e-01  2.3949e-01  2.5458e+00  3.6111e-01
  3.9486e-02  4.8607e-01 -3.6974e-01  5.7282e-02 -4.9317e-01  2.2765e-01
  7.9966e-01  2.1428e-01  6.9811e-01  1.1262e+00 -1.3526e-01  7.1972e-01
 -9.9605e-04 -2.6842e-01 -8.3038e-01  2.1780e-01  3.4355e-01  3.7731e-01
 -4.0251e-01  3.3124e-01  1.2576e+00 -2.7196e-01 -8

In [8]:
print(word_vectors['computer'].shape)

(100,)


In [9]:
print(word_vectors.most_similar(positive=['king','woman'], negative=['man'], topn=10))

[('queen', 0.7698540687561035), ('monarch', 0.6843380928039551), ('throne', 0.6755735874176025), ('daughter', 0.6594555974006653), ('princess', 0.6520534157752991), ('prince', 0.6517034769058228), ('elizabeth', 0.6464517712593079), ('mother', 0.631171703338623), ('emperor', 0.6106470823287964), ('wife', 0.6098655462265015)]


In [12]:
#Example of calculating similarity

print(word_vectors.similarity('woman','man'))
print(word_vectors.similarity('king','queen'))
print(word_vectors.similarity('uncle','aunt'))
print(word_vectors.similarity('boy','girl'))
print(word_vectors.similarity('friend','boss'))


0.8323494
0.7507691
0.7587473
0.917573
0.56475115


In [15]:
print(word_vectors.most_similar("ceo", topn=5)) # most similar

[('executive', 0.8861948847770691), ('chairman', 0.7696428298950195), ('chief', 0.7450050115585327), ('cfo', 0.7056118249893188), ('vice', 0.6872465014457703)]


In [18]:
# vector similarity
import numpy as np
#words to compare

word1 = 'man'
word2 = 'woman'

word3 = 'semiconductor'
word4 = 'earthworm'

word5 = 'nephew'
word6 = 'niece'

#Calculate the vector difference
vector_diff1 = model[word1] - model[word2]
vector_diff2 = model[word3] - model[word4]
vector_diff3 = model[word5] - model[word6]

#Calculate the magnitude of the vector diff
magnitude_of_diff1 = np.linalg.norm(vector_diff1)
magnitude_of_diff2 = np.linalg.norm(vector_diff2)
magnitude_of_diff3 = np.linalg.norm(vector_diff3)

#Print the magnitude of the difference
print("The magnitude of the diff between '{}' and '{}' is {:.2f}".format(word1,word2,magnitude_of_diff1))
print("The magnitude of the diff between '{}' and '{}' is {:.2f}".format(word3,word4,magnitude_of_diff2))
print("The magnitude of the diff between '{}' and '{}' is {:.2f}".format(word5,word6,magnitude_of_diff3))



The magnitude of the diff between 'man' and 'woman' is 3.36
The magnitude of the diff between 'semiconductor' and 'earthworm' is 7.73
The magnitude of the diff between 'nephew' and 'niece' is 2.83


CREATING TOKEN EMBEDDINGS

In [1]:
import torch

input_ids = torch.tensor([2, 3, 5, 1])
print(input_ids)
print(input_ids.dtype)   # shows the data type
print(input_ids.shape)   # shows tensor shape


tensor([2, 3, 5, 1])
torch.int64
torch.Size([4])


In [2]:

import torch

vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [3]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [4]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [5]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
